# [package]
# name = "yac"
# version = "0.1.0"
# edition = "2024"

[workspace]
members = [ "crates/yac-server"]
resolver = "3"

[workspace.dependencies]
log = "0.4.17"
serde_json = "1.0.108"
serde = { version = "1.0.216" }
serde_derive = { version = "1.0.216" }
crossbeam-channel = "0.5.14"
