const std = @import("std");
const json = @import("../json_utils.zig");
const vim = @import("../vim_protocol.zig");
const registry_mod = @import("../lsp/registry.zig");
const LspClient = @import("../lsp/client.zig").LspClient;
const log = @import("../log.zig");
pub const treesitter_mod = @import("../treesitter/treesitter.zig");
const queue_mod = @import("../queue.zig");
const lsp_mod = @import("../lsp/lsp.zig");
const clients_mod = @import("../clients.zig");
pub const lsp_transform = @import("../lsp/transform.zig");

const dap_session_mod = @import("../dap/session.zig");

const Allocator = std.mem.Allocator;
pub const Value = json.Value;
const ObjectMap = json.ObjectMap;
const LspRegistry = registry_mod.LspRegistry;
const ClientId = clients_mod.ClientId;

// ============================================================================
// Handler Context
// ============================================================================

pub const HandlerContext = struct {
    /// Arena allocator for request-scope temporary allocations.
    allocator: Allocator,
    /// GPA allocator for allocations that must outlive the request (e.g. OutMessage bytes).
    gpa_allocator: Allocator,
    registry: *LspRegistry,
    lsp_state: *lsp_mod.Lsp,
    client_stream: std.net.Stream,
    client_id: ClientId,
    ts: ?*treesitter_mod.TreeSitter = null,
    /// Active DAP debug session (single session at a time).
    dap_session: *?*dap_session_mod.DapSession = undefined,
    /// Outgoing message queue — push OutMessages here instead of writing directly.
    out_queue: *queue_mod.OutQueue,
    /// Set to true to request daemon shutdown.
    shutdown_flag: *bool = undefined,

    // -- Framework state (set by handlers, read by event_loop after dispatch) --

    /// LSP request in flight — event_loop will track and route the response.
    _pending: ?PendingLsp = null,
    /// Request should be deferred (LSP still initializing).
    _deferred: bool = false,
    /// Subscribe this client to workspace change notifications.
    _subscribe_workspace: ?[]const u8 = null,

    pub const PendingLsp = struct {
        request_id: u32,
        client_key: ?[]const u8 = null,
        transform: lsp_transform.TransformFn = lsp_transform.transformIdentity,
    };

    // -- LSP convenience methods --

    /// Resolve LSP context for a file. Returns null if unavailable.
    /// If the LSP is still initializing, sets `_deferred = true` and returns null.
    pub fn lsp(self: *HandlerContext, file: []const u8) ?LspContext {
        const result = getLspContextForFileEx(self, file, true) catch return null;
        switch (result) {
            .ready => |c| return c,
            .initializing => {
                self._deferred = true;
                return null;
            },
            .not_available => return null,
        }
    }

    /// Like lsp(), but doesn't require the client to be fully initialized.
    pub fn lspAllowInit(self: *HandlerContext, file: []const u8) ?LspContext {
        const result = getLspContextForFileEx(self, file, false) catch return null;
        switch (result) {
            .ready => |c| return c,
            .initializing, .not_available => return null,
        }
    }

    /// Send an LSP request and track it for async response routing.
    /// `request` must be a typed LSP request (generated by `LspRequest`).
    /// After calling this, the handler should return null — the response will
    /// arrive later via the LSP response callback path.
    pub fn lspRequest(self: *HandlerContext, client: *LspClient, request: anytype, opts: LspRequestOpts) !void {
        const request_id = try client.request(request);
        self._pending = .{
            .request_id = request_id,
            .client_key = opts.client_key,
            .transform = opts.transform,
        };
    }

    pub const LspRequestOpts = struct {
        client_key: ?[]const u8 = null,
        transform: lsp_transform.TransformFn = lsp_transform.transformIdentity,
    };

    /// Mark a workspace URI for client subscription (checked by event_loop after dispatch).
    pub fn subscribeWorkspace(self: *HandlerContext, uri: []const u8) void {
        self._subscribe_workspace = uri;
    }

    /// Send a Vim ex command via the out_queue (non-blocking; drops if queue full).
    pub fn vimEx(self: *HandlerContext, command: []const u8) !void {
        const encoded = try vim.encodeChannelCommand(self.allocator, .{ .ex = .{ .command = command } });
        defer self.allocator.free(encoded);
        const msg = try self.gpa_allocator.alloc(u8, encoded.len + 1);
        @memcpy(msg[0..encoded.len], encoded);
        msg[encoded.len] = '\n';
        if (!self.out_queue.push(.{ .stream = self.client_stream, .bytes = msg })) {
            self.gpa_allocator.free(msg);
            log.warn("vimEx: out queue full, dropping command", .{});
        }
    }

    /// Send a Vim call_async command via the out_queue (non-blocking; drops if queue full).
    pub fn vimCallAsync(self: *HandlerContext, func: []const u8, args: Value) !void {
        const encoded = try vim.encodeChannelCommand(self.allocator, .{ .call_async = .{
            .func = func,
            .args = args,
        } });
        defer self.allocator.free(encoded);
        const msg = try self.gpa_allocator.alloc(u8, encoded.len + 1);
        @memcpy(msg[0..encoded.len], encoded);
        msg[encoded.len] = '\n';
        if (!self.out_queue.push(.{ .stream = self.client_stream, .bytes = msg })) {
            self.gpa_allocator.free(msg);
            log.warn("vimCallAsync: out queue full, dropping call", .{});
        }
    }
};

// ============================================================================
// LSP context resolution (internal)
// ============================================================================

pub const LspContext = struct {
    language: []const u8,
    client_key: []const u8,
    uri: []const u8,
    client: *LspClient,
    real_path: []const u8,
};

/// Result of trying to get LSP context (internal — handlers use ctx.lsp() instead).
pub const LspContextResult = union(enum) {
    ready: LspContext,
    initializing: void,
    not_available: void,
};

// -- Common return types (shared across handlers) --

pub const OkResult = struct { ok: bool };
pub const PendingResult = struct { pending: bool };

/// Common param type: file path only.
pub const FileParams = struct {
    file: ?[]const u8 = null,
};

/// Common param type: file + position.
pub const PositionParams = struct {
    file: ?[]const u8 = null,
    line: ?i64 = null,
    column: ?i64 = null,
};

/// Get LSP context from a file path, optionally allowing initializing clients.
pub fn getLspContextForFileEx(ctx: *HandlerContext, file: []const u8, require_ready: bool) !LspContextResult {
    const real_path = registry_mod.extractRealPath(file);

    const language = LspRegistry.detectLanguage(real_path) orelse {
        log.debug("No language detected for {s}", .{real_path});
        return .{ .not_available = {} };
    };

    // Skip repeated spawn attempts for servers known to be unavailable
    if (ctx.registry.hasSpawnFailed(language)) {
        return .{ .not_available = {} };
    }

    const result = ctx.registry.getOrCreateClient(language, real_path) catch |e| {
        log.err("LSP server not available for {s}: {any}", .{ language, e });
        ctx.registry.markSpawnFailed(language);
        const config = LspRegistry.getConfig(language);
        const cmd = if (config) |c| c.command else language;
        // Safety: reject values containing single quotes to prevent Vim command injection
        if (std.mem.indexOfScalar(u8, language, '\'') != null or
            std.mem.indexOfScalar(u8, cmd, '\'') != null)
        {
            return .{ .not_available = {} };
        }
        const msg = std.fmt.allocPrint(ctx.allocator, "call yac_install#on_spawn_failed('{s}', '{s}')", .{ language, cmd }) catch {
            return .{ .not_available = {} };
        };
        ctx.vimEx(msg) catch {};
        return .{ .not_available = {} };
    };

    if (require_ready and ctx.registry.isInitializing(result.client_key)) return .{ .initializing = {} };

    const uri = try registry_mod.filePathToUri(ctx.allocator, real_path);

    return .{ .ready = .{
        .language = language,
        .client_key = result.client_key,
        .uri = uri,
        .client = result.client,
        .real_path = real_path,
    } };
}

// LSP protocol types are in lsp/types.zig — import directly where needed.

/// Build contentChanges Value from either a forwarded Value or raw text.
pub fn buildContentChanges(allocator: Allocator, changes: ?Value, text: ?[]const u8) !?Value {
    if (changes) |c| return c;
    if (text) |t| {
        var arr = std.json.Array.init(allocator);
        try arr.append(try json.structToValue(allocator, ContentChange{ .text = t }));
        return .{ .array = arr };
    }
    return null;
}

const ContentChange = struct {
    text: []const u8,
};

/// Check if the server supports a capability; if not, send a toast and return true (= unsupported).
pub fn checkUnsupported(ctx: *HandlerContext, client_key: []const u8, capability: []const u8, feature_name: []const u8) bool {
    if (!ctx.registry.serverSupports(client_key, capability)) {
        const msg = std.fmt.allocPrint(ctx.allocator, "call yac#toast('[yac] Server does not support {s}')", .{feature_name}) catch return true;
        ctx.vimEx(msg) catch {};
        return true;
    }
    return false;
}
