const std = @import("std");
const json = @import("../json_utils.zig");
const lsp = @import("protocol.zig");
const types = @import("types.zig");
const log = @import("../log.zig");

const Allocator = std.mem.Allocator;
const Value = json.Value;

// LSP Initialize param types are in types.zig.
const InitializeParams = types.InitializeParams;
const WorkspaceFolder = types.WorkspaceFolder;

// ============================================================================
// LSP Client - manages a single language server process
//
// Spawns a child process, communicates via Content-Length framed JSON-RPC.
// Each client owns its child process and framer state.
// ============================================================================

pub const LspState = enum {
    uninitialized,
    initializing,
    initialized,
    shutting_down,
    shutdown,
};

pub const PendingRequest = struct {};

pub const LspClient = struct {
    allocator: Allocator,
    child: std.process.Child,
    framer: lsp.MessageFramer,
    state: LspState,
    next_id: *std.atomic.Value(u32),
    pending_requests: std.AutoHashMap(u32, PendingRequest),
    /// Buffer for reading from child stdout
    read_buf: [4096]u8,

    pub fn spawn(allocator: Allocator, command: []const u8, args: []const []const u8, next_id: *std.atomic.Value(u32)) !*LspClient {
        var argv: std.ArrayList([]const u8) = .{};
        defer argv.deinit(allocator);
        try argv.append(allocator, command);
        try argv.appendSlice(allocator, args);

        var child = std.process.Child.init(argv.items, allocator);
        child.stdin_behavior = .Pipe;
        child.stdout_behavior = .Pipe;
        child.stderr_behavior = .Pipe;

        try child.spawn();

        const client = try allocator.create(LspClient);
        client.* = .{
            .allocator = allocator,
            .child = child,
            .framer = lsp.MessageFramer.init(allocator),
            .state = .uninitialized,
            .next_id = next_id,
            .pending_requests = std.AutoHashMap(u32, PendingRequest).init(allocator),
            .read_buf = undefined,
        };

        return client;
    }

    pub fn deinit(self: *LspClient) void {
        self.framer.deinit();
        self.pending_requests.deinit();
        _ = self.child.kill() catch {};
        _ = self.child.wait() catch {};
        self.allocator.destroy(self);
    }

    /// Get the stdout fd for polling.
    pub fn stdoutFd(self: *LspClient) std.posix.fd_t {
        return self.child.stdout.?.handle;
    }

    /// Send a pre-constructed Message (serialize + frame + write).
    pub fn send(self: *LspClient, msg: lsp.Message) !void {
        const data = try msg.serialize(self.allocator);
        defer self.allocator.free(data);

        const stdin = self.child.stdin orelse return error.StdinClosed;
        try stdin.writeAll(data);
    }

    /// Send a typed LSP request and return the request ID.
    /// `req` must be a type generated by `LspRequest(method, Params)`.
    pub fn request(self: *LspClient, req: anytype) !u32 {
        const T = @TypeOf(req);
        if (!@hasDecl(T, "method")) @compileError("request() expects a typed request (use lsp.LspRequest), got " ++ @typeName(T));

        // fetchAdd returns the old value; skip 0 (reserved as "no id")
        var id = self.next_id.fetchAdd(1, .monotonic);
        if (id == 0) id = self.next_id.fetchAdd(1, .monotonic);

        var arena = std.heap.ArenaAllocator.init(self.allocator);
        defer arena.deinit();
        try self.send(.{ .request = .{
            .id = .{ .integer = @intCast(id) },
            .method = T.method,
            .params = try json.structToValue(arena.allocator(), req.params),
        } });

        try self.pending_requests.put(id, .{});
        log.debug("LSP request [{d}]: {s}", .{ id, T.method });
        return id;
    }

    /// Send $/cancelRequest notification for a pending request.
    pub fn cancelRequest(self: *LspClient, request_id: u32) !void {
        const CancelNotification = lsp.LspNotification("$/cancelRequest", struct { id: i64 });
        try self.notify(CancelNotification{ .params = .{ .id = @intCast(request_id) } });
    }

    /// Send a typed LSP notification (no response expected).
    /// `notification` must be a type generated by `LspNotification(method, Params)`.
    pub fn notify(self: *LspClient, notification: anytype) !void {
        const T = @TypeOf(notification);
        if (!@hasDecl(T, "method")) @compileError("notify() expects a typed notification (use lsp.LspNotification), got " ++ @typeName(T));

        var arena = std.heap.ArenaAllocator.init(self.allocator);
        defer arena.deinit();
        try self.send(.{ .notification = .{
            .method = T.method,
            .params = try json.structToValue(arena.allocator(), notification.params),
        } });
        log.debug("LSP notification: {s}", .{T.method});
    }

    /// Read and parse any available messages from stdout.
    /// Returns parsed JSON responses. Caller must deinit each parsed value.
    pub fn readMessages(self: *LspClient) !std.ArrayList(LspMessage) {
        const stdout = self.child.stdout orelse return error.StdoutClosed;
        const n = stdout.read(&self.read_buf) catch |err| {
            if (err == error.WouldBlock) {
                return .{};
            }
            return err;
        };

        if (n == 0) return error.ConnectionReset;

        var raw_messages = try self.framer.feedData(self.allocator, self.read_buf[0..n]);
        defer {
            for (raw_messages.items) |msg| self.allocator.free(msg);
            raw_messages.deinit(self.allocator);
        }

        var messages: std.ArrayList(LspMessage) = .{};
        errdefer {
            for (messages.items) |*msg| msg.deinit();
            messages.deinit(self.allocator);
        }

        for (raw_messages.items) |raw_msg| {
            const parsed = try json.parse(self.allocator, raw_msg);
            const msg = lsp.Message.fromValue(self.allocator, parsed.value) orelse {
                parsed.deinit();
                continue;
            };

            // Remove pending request tracking for responses
            switch (msg) {
                .response => |resp| {
                    if (resp.id.asU32()) |int_id| _ = self.pending_requests.remove(int_id);
                },
                else => {},
            }

            try messages.append(self.allocator, .{ .parsed = parsed, .kind = msg });
        }

        return messages;
    }

    /// Initialize the LSP server with the given workspace root.
    pub fn initialize(self: *LspClient, workspace_uri: ?[]const u8) !u32 {
        self.state = .initializing;

        // Build workspaceFolders array if workspace is provided
        var ws_folders: ?Value = null;
        const root_uri: Value = if (workspace_uri) |uri| blk: {
            var folders = std.json.Array.init(self.allocator);
            try folders.append(try json.structToValue(self.allocator, WorkspaceFolder{ .uri = uri, .name = "workspace" }));
            ws_folders = .{ .array = folders };
            break :blk json.jsonString(uri);
        } else .null;

        return try self.request(types.Initialize{ .params = .{
            .processId = @intCast(std.c.getpid()),
            .capabilities = .{
                .textDocument = .{
                    .completion = .{ .dynamicRegistration = false },
                    .signatureHelp = .{
                        .dynamicRegistration = false,
                        .signatureInformation = .{
                            .documentationFormat = .{ .array = std.json.Array.init(self.allocator) },
                            .parameterInformation = .{ .labelOffsetSupport = true },
                            .activeParameterSupport = true,
                        },
                    },
                    .hover = .{ .dynamicRegistration = false },
                    .definition = .{ .dynamicRegistration = false },
                    .declaration = .{ .dynamicRegistration = false },
                    .typeDefinition = .{ .dynamicRegistration = false },
                    .implementation = .{ .dynamicRegistration = false },
                    .references = .{ .dynamicRegistration = false },
                    .synchronization = .{ .didSave = true, .willSave = true },
                    .publishDiagnostics = .{ .relatedInformation = true },
                },
                .workspace = .{
                    .applyEdit = true,
                    .symbol = .{ .dynamicRegistration = false },
                },
                .window = .{ .workDoneProgress = true },
            },
            .rootUri = root_uri,
            .workspaceFolders = ws_folders,
            .clientInfo = .{ .name = "yac.vim", .version = "0.1.0" },
        } });
    }

    /// Initialize a Copilot language server with Copilot-specific capabilities.
    pub fn initializeCopilot(self: *LspClient) !u32 {
        self.state = .initializing;

        return try self.request(types.Initialize{ .params = .{
            .processId = @intCast(std.c.getpid()),
            .capabilities = .{
                .textDocument = .{
                    .inlineCompletion = .{ .dynamicRegistration = true },
                    .synchronization = .{ .didSave = true },
                },
            },
            .rootUri = .null,
            .clientInfo = .{ .name = "yac.vim", .version = "0.1.0" },
            .initializationOptions = .{
                .editorInfo = .{ .name = "yac.vim", .version = "0.1.0" },
                .editorPluginInfo = .{ .name = "yac-copilot", .version = "0.1.0" },
            },
        } });
    }

    /// Send initialized notification after receiving initialize response.
    pub fn sendInitialized(self: *LspClient) !void {
        self.state = .initialized;
        try self.notify(types.Initialized{ .params = .{} });
    }

    /// Send shutdown request.
    pub fn sendShutdown(self: *LspClient) !u32 {
        self.state = .shutting_down;
        return try self.request(types.Shutdown{ .params = .null });
    }

    /// Send exit notification.
    pub fn sendExit(self: *LspClient) !void {
        self.state = .shutdown;
        try self.notify(types.Exit{ .params = .null });
    }
};

/// A parsed LSP message with ownership of the underlying JSON.
pub const LspMessage = struct {
    parsed: std.json.Parsed(Value),
    kind: lsp.Message,

    pub fn deinit(self: *LspMessage) void {
        self.parsed.deinit();
    }
};
